apiVersion: v1
kind: Service
metadata:
  name: unifica
  namespace: unifica
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: unifica
  sessionAffinity: None