replicaCount: 1
image:
  repository: api-dry-k8s
  pullPolicy: IfNotPresent
  tag: 1.3
imagePullSecrets: []
nameOverride: ''
fullnameOverride: api-dry
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
  containerPort: 80
ingress:
  enabled: false
  className: ''
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
  hosts:
    - host: example.com.br
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
configmapname: api-dry
data:
  DATABASE_HOST: 
  DATABASE_USER: 
  DATABASE_PASSWORD: 
  DATABASE_NAME: 
  DATABASE_SCHEMA: 
  DATABASE_PORT: '5432'
  SERVER_PORT: '80'
  TZ: America/Sao_Paulo
  